// <auto-generated />
using GasHimApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GasHimApi.Data.Migrations
{
    [DbContext(typeof(ChemicalDbContext))]
    [Migration("20250729152522_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GasHimApi.Data.Models.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ByProducts")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrimaryFeedstocks")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryProducts")
                        .HasColumnType("text");

                    b.Property<string>("SecondaryFeedstocks")
                        .HasColumnType("text");

                    b.Property<double>("YieldPercentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("GasHimApi.Data.Models.Substance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Synonyms")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Substances");
                });
#pragma warning restore 612, 618
        }
    }
}
